# Generated by Django 6.0.3 on 2026-04-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_reminder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='follow',
            new_name='users_follo_followi_f3cd22_idx',
            old_name='users_follo_followi_2b5fbd_idx',
        ),
    ]
