# Generated by Django 6.0.3 on 2026-04-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification_postcollaboration_comment_feedpostseen'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='users_comme_post_ow_947a98_idx',
            old_name='users_commen_post_ow_3d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='feedpostseen',
            new_name='users_feedp_viewer__decaa2_idx',
            old_name='users_feedpos_viewer_6g7h8i_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='users_notif_user_id_2c9cd4_idx',
            old_name='users_notifi_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='users_notif_user_id_02c2a2_idx',
            old_name='users_notifi_user_id_2m3n4o_idx',
        ),
        migrations.RenameIndex(
            model_name='postcollaboration',
            new_name='users_postc_collabo_1decdc_idx',
            old_name='users_postco_collabo_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='yaqinrequest',
            new_name='users_yaqin_to_user_fdcdf1_idx',
            old_name='users_yaqin_to_user_status',
        ),
        migrations.RenameIndex(
            model_name='yaqinrequest',
            new_name='users_yaqin_from_us_c42ae5_idx',
            old_name='users_yaqin_from_user_status',
        ),
    ]
