# Generated by Django 6.0.3 on 2026-04-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_dmthread'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dmthread',
            new_name='users_dmthr_user_lo_285415_idx',
            old_name='users_dmthr_user_lo_7a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='dmthread',
            new_name='users_dmthr_user_hi_558d48_idx',
            old_name='users_dmthr_user_hi_7a8b9d_idx',
        ),
    ]
