# Generated by Django 6.0.3 on 2026-04-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_users_dmthr_user_lo_7a8b9c_idx_users_dmthr_user_lo_285415_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('yaqin_request', 'Yaqinlik so‘rovi'), ('collab_invite', 'Postga ulashish'), ('dm_message', 'Shaxsiy xabar')], db_index=True, max_length=32),
        ),
    ]
