# Generated by Django 6.0.3 on 2026-04-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_comment_extra_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='users_comme_post_ow_a2a496_idx',
            old_name='users_comment_owner_post_created_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='users_comme_author__97239b_idx',
            old_name='users_comment_author_created_desc_idx',
        ),
    ]
