# Generated by Django 6.0.3 on 2026-04-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notification_more_kinds'),
        ('users', '0012_rename_users_comment_owner_post_created_idx_users_comme_post_ow_a2a496_idx_and_more'),
    ]

    operations = [
    ]
