# Generated by Django 6.0.3 on 2026-04-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0005_charity_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='charityupdate',
            new_name='charities_c_charity_6c0a00_idx',
            old_name='charities_c_charity__f8f8cd_idx',
        ),
    ]
