# Generated by Django 6.0.3 on 2026-04-02 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Sarlavha')),
                ('body', models.TextField(max_length=255, verbose_name='Xabar matni')),
                ('hashtag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hashtag')),
                ('mood', models.CharField(choices=[('happy', '😊 Yaxshi'), ('sad', '😔 Ma’yus'), ('energy', '⚡ Energiya'), ('work', '🛠️ Ish bilan band'), ('dream', '☁️ Xayolparast')], default='dream', max_length=10, verbose_name='Kayfiyat')),
                ('is_public', models.BooleanField(default=False, verbose_name='Ochiq post')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='blogs.post', verbose_name='Zanjir boshi')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
