# Generated by Django 6.0.3 on 2026-04-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='blogs_post_author__851d87_idx',
            old_name='blogs_post_author_created_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blogs_post_author__452ac4_idx',
            old_name='blogs_post_author_created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blogs_post_hashtag_1c8024_idx',
            old_name='blogs_post_hashtag_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blogs_post_is_publ_9476a0_idx',
            old_name='blogs_post_public_created_desc_idx',
        ),
    ]
